### ISSUE TITLE
Installation - Please make sure you have the correct access rights

### ISSUE THREAD

**Issue by ariasamin** [broadinstitute/funpipe#58]
Hello, 
Would you please help me with this error?
Best of all, 
Narges

[narges@node1922 ~]$ git clone git@github.com:broadinstitute/funpipe.git
Cloning into 'funpipe'...
Warning: Permanently added the ECDSA host key for IP address '140.82.113.4' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by xiaoli0** [comment]
Hi, I believe this has to do with your own github setup. You need to add your ssh key pair into your github account. You can refer to this link. https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account
